### 1. Importando a Biblioteca

A convenção universal da comunidade é importar o Pandas com alias pd.

In [1]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/75/08/67cc404b3a966b6df27b38370ddd96b3b023030b572283d035181854aac5/pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata
  Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\0201392321021\appdata\roaming\python\python312\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\0201392321021\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Obtaining dependency information for tzdata from https://files.pythonhosted.org/packages/c7/b0/003792df09decd6849a5e39c28b513c06e84436a54440380862b5aeff25d/tzdata-2025.3-py2.py3-none-any.whl.metadata
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\0201392321021\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 11.1 MB/s eta 0:00:01
   ----- ---------------------------------- 1.5/9.7 MB 15.4 MB/s eta 0:00:01
   --------- ------------------------------ 2.4/9.7 MB 17.1 MB/s eta 0:00:01
   ------------- -------------------------- 3.3/9.7 MB 17.5 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.7 MB 17.9 MB/s eta 0:00:01
   --------------------- ------------------ 5.1/9.7 MB 18.2 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.7 MB 18.3 MB/s eta 0:00:01
   ---------------------------- ----------- 7.0/9.7 MB 18.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 18.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 18.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 18.9 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 17.8 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
   ---------------------------------------- 0.0/348.5 kB ? eta -:--:--
   --------------------------------------- 348.5/348.5 kB 22.6 MB/s eta 0:00:00
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np #frequentimente usamos junto com o Pandas

print(f"Versão do Pandas: {pd.__version__}")

Versão do Pandas: 3.0.1

Series: É uma matriz unidimensional com rótulos(indices), Pode ser vista como uma unica coluna de uma tabela.

DataFrame: É uma estrutura bidimensional(Linhas e colunas), como uma pilha completa. É essencialmebte um conjunto de series.

In [4]:
# Criando uma Series
notas = pd.Series([8.5, 9.0, 7.5, 10.0], index=['Aluno A', 'Aluno B', 'Aluno C', 'Aluno D'])
print("Exemplo de Series:\n", notas, "\n")

Exemplo de Series:
 Aluno A     8.5
Aluno B     9.0
Aluno C     7.5
Aluno D    10.0
dtype: float64

In [ ]:
# Criando um DataFrame a partir de um dicionário(útil para testes locais)
dados_turma = {
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana'],
    'Idade': [20, 22, 21, 23],
    'Nota_Final': [8.5, 7.0, 9.5, 6.5],
    'Aprovado': [True, True, True, False]

    df = pd.DataFrame(dados_turma)
    print("Exemplo de DataFrame")
}

In [5]:
# O comando abaixo é o padrão para ler arquivos CSV
#df_csv = pd.read_csv('caminho/para/seuarquivo.csv')

#Exemplo pratico carregando um datasset público diretamnete de uma URL para demonstração:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_titanic = pd.read_csv(url)
print("Dados carregados com sucesso!")

Dados carregados com sucesso!

In [6]:
# . head() mostra as 5 primeiras linhas do DataFrame
display(df_titanic.head())

print("\n--- Formato do Dataset (linhas, colunas) ---")
print(df_titanic.shape)

print("\n--- Informações Gerais e Tipos de Dados ---")
df_titanic.info()

print("\n--- Resumo Estático das colunas Numéricas ---")
display(df_titanic.describe())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

--- Formato do Dataset (linhas, colunas) ---
(891, 12)

--- Informações Gerais e Tipos de Dados ---
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

--- Resumo Estático das colunas Numéricas ---

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# Selecionando apenas uma coluna (retorna uma Series)
idades = df_titanic['Age']

#Selecionando multiplas colunas (retorna um novo DataFrame)
df_reduzido = df_titanic[['Name', 'Age', 'Survived']]

#Filtragem (Querying): Selecionando apenas passageiros com mais de 60 anos
passageiros_idosos = df_titanic[df_titanic['Age'] > 60]
print